services:
  #  comment out server for local development
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_DB_URL=${SERVICE_DB_URL}
      - SERVICE_DB_LOGIN=${SERVICE_DB_LOGIN}
      - SERVICE_DB_PASSWORD=${SERVICE_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    ports:
      - "8080:8080"
    depends_on:
      postgresdb:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  postgresdb:
    image: postgres:17
    environment:
      POSTGRES_USER: ${SERVICE_DB_LOGIN}
      POSTGRES_PASSWORD: ${SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${SERVICE_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SERVICE_DB_LOGIN} -d ${SERVICE_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # api
      - "9001:9001"  # web console
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  minio-data:
