services:
  #  comment out server for local development
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_DB_URL=${SERVICE_DB_URL}
      - SERVICE_DB_LOGIN=${SERVICE_DB_LOGIN}
      - SERVICE_DB_PASSWORD=${SERVICE_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:17
    environment:
      POSTGRES_USER: ${SERVICE_DB_LOGIN}
      POSTGRES_PASSWORD: ${SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${SERVICE_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # api
      - "9001:9001"  # web console
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  minio-data:
